### ISSUE TITLE
access normals from gridmap variable

### ISSUE THREAD

**Issue by mcamurri** [ethz-asl/grid_map#102]
I have a question: from the RViz I can see that the gridmap is visualized with some sort of normal to orient the cell/mesh. This means that for each cell a normal is computed. Is it available from the gridmap object or it is computed by the RViz plugin from the neighbors?

Is there a method to get the normals automatically?

**Comment by pfankhauser** [comment]
Hi @mcamurri,
We have implemented surface normal estimation as part of [Elevation Mapping](https://github.com/ethz-asl/elevation_mapping) and as a Grid Map Filter in [Traversability Estimation](https://github.com/ethz-asl/traversability_estimation). We are planning to unify the implementation as a Grid Map Filter in this repo, but in the meanwhile you can use the other implementations.

**Comment by pfankhauser** [comment]
It's here! We have a new implementation for several grid map filters, including normal vector estimation. More info [here](https://github.com/ethz-asl/grid_map/blob/master/README.md#grid_map_filters).

![Filters demo results](https://github.com/ethz-asl/grid_map/blob/master/grid_map_demos/doc/filters_demo.gif?raw=true)
