### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by artivis** [ethz-asl/grid_map#131]
While compiling `grid_map_rviz_plugin` master branch on Ubuntu 14 with a bunch of compilation flag set I got the following compilation error :

`grid_map_rviz_plugin/src/GridMapVisual.cpp:73:18: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]`

**Comment by pfankhauser** [comment]
Thanks for reporting, @artivis! I just fixed this.
