### ISSUE TITLE
Is GridMap rviz rendering one cell short ?

### ISSUE THREAD

**Issue by artivis** [ethz-asl/grid_map#136]
Not sure if it is actually an issue but when overlaying an occupancy grid and a grid map, the two plots mismatch - see attached screenshot. Visually it looks like grid map is one cell short.  
I noticed that in the [GridMapVisual](https://github.com/ethz-asl/grid_map/blob/master/grid_map_rviz_plugin/src/GridMapVisual.cpp#L132) class cells are iterated up to `rows\cols` **-1**.  

Is this the intended behavior ? What is the rational behind this ?

![screenshot from 2017-10-15 15-56-42](https://user-images.githubusercontent.com/6572747/31585484-a6d75402-b1c2-11e7-939f-0a77ee3a35de.png)

Simple 50x50 square fully marked as occupied. The occupancy grid overflow on each side (black border). Moreover, the grid map displayed is only 49x49.

![screenshot from 2017-10-15 15-59-16](https://user-images.githubusercontent.com/6572747/31585485-a6ee8bfe-b1c2-11e7-83ba-c2785fd78836.png)

**Comment by pfankhauser** [comment]
Occupancy grid renders a square per grid map entry and the grid map rviz visualization creates a mesh where the vertices are located in the cell center. That's why you see a half a cell width difference. Does this answer your question?

**Comment by artivis** [comment]
Yes it does. Thanks !
Closing this.
