### ISSUE TITLE
If I would like to make a semi-circle iterator, how do I go about doing so?

### ISSUE THREAD

**Issue by CtfChan** [ethz-asl/grid_map#168]

**Comment by pfankhauser** [comment]
You could use the [`PolygonIterator`](https://github.com/ethz-asl/grid_map/blob/master/grid_map_core/include/grid_map_core/iterators/PolygonIterator.hpp) to define your custom shape or write your own custom iterator.

**Comment by CtfChan** [comment]
I see. Thank you for your help!

**Comment by CtfChan** [comment]
Thank you for your help kind sir.
