### ISSUE TITLE
Gridmap for large areas

### ISSUE THREAD

**Issue by murikill** [ethz-asl/grid_map#169]
Hello, 

it is possible to use grid_map for large areas (memory efficient)? 
For example 10000 x 10000 gridcells.

Thank you

**Comment by pfankhauser** [comment]
Hi @murikill, Grid Map builds on Eigen dense matrices, so this should scale well for large data. However, you will have to take care to manipulate the data efficiently, for more details on this see [here](https://github.com/ethz-asl/grid_map#iterators). Please let me know if you gain more experience.

**Comment by bryanibit** [comment]
@murikill Did you finish the large scale mapping?

**Comment by murikill** [comment]
@bryanibit I'm using grid_map for small maps. For large matrices you need to have a lot of memory on your pc.

**Comment by bryanibit** [comment]
@murikill can you provide some thoughts about mosaic pointclouds to a large map with grid_map?
