### ISSUE TITLE
resize() with initial value?

### ISSUE THREAD

**Issue by huang-qiao** [ethz-asl/grid_map#38]
Regarding to `GridMap::add(const std::string& layer, const double value)`, we can add layers with initial value. However, `GridMap::resize(const Eigen::Array2i& size)` only resize all layers without filling any data. 

If I want to extend all layers with their initial value, is there any way to do that?

Thanks.

**Comment by pfankhauser** [comment]
The `GridMap::resize(...)` method is actually `private`, so you won't be able to access it from outside. The better way to change the dimensions of your map is to use the `GridMap::setGeometry(...)` method. For example:

``
map.setGeometry(Length(1.2, 2.0), 0.03);
``

Be aware that this method clears all the data in the map. If you want to give all the cells in a layer (or possibly all the layers) the same value, you can easily achieve this with:

``
for (const auto& layer : map.getLayers()) {
map[layer].setConstant(12.0);
}
``

Let me know if you need more information.
