### ISSUE TITLE
New api GridMapRosConverter::toMessagePtr()

### ISSUE THREAD

**Issue by stonier** [ethz-asl/grid_map#46]
Useful if you want to fling around grid map messages in nodelets without copying data.

I can probably contribute this when I start optimising.

**Comment by pfankhauser** [comment]
I'd be happy to integrate this if you take a shot at it, thanks.

**Comment by stonier** [comment]
This is not necessary. Perfectly ok to have the following code:

```
auto msg_ptr = std::make_shared<grid_map_msgs::GridMap>();
toMessage(some_grid_map_object, *msg_ptr);
```
