### ISSUE TITLE
Scaling of output in GridMapRosConverter::addLayerFromImage

### ISSUE THREAD

**Issue by solosuper** [ethz-asl/grid_map#49]
Hi everyone,
When scaling the `height` in [addLayerFromImage](https://github.com/ethz-asl/grid_map/blob/master/grid_map_ros/src/GridMapRosConverter.cpp#L408), shouldn't the denominator be  `depth - 1`?

**Comment by pfankhauser** [comment]
Thanks for pointing this out, I think you are right. Is the issue that you experience that full black or white values are not exactly mapped to the specified lower/upper value? What do you think @martiwer?

**Comment by martiwer** [comment]
Yes, I think the denominator should be `depth - 1 `.

**Comment by pfankhauser** [comment]
This has been resolved in #50.
