### ISSUE TITLE
missing config folder in grid_map_demos

### ISSUE THREAD

**Issue by procopiostein** [ethz-asl/grid_map#79]
the config folder from grid_map_demos is not present in the indigo .deb:

roslaunch grid_map_demos tutorial_demo.launch

error loading <rosparam> tag: 
	file does not exist [/opt/ros/indigo/share/grid_map_demos/config/tutorial_demo.yaml]
XML is <rosparam command="load" file="$(find grid_map_demos)/config/tutorial_demo.yaml"/>
The traceback for the exception was written to the log file

**Comment by stonier** [comment]
Must be a very old release, that went in commit 93ca546f in Jan 2016 and is present in my indigo deb install of the project.

**Comment by pfankhauser** [comment]
@procopiostein did an update resolve the issue?
