### ISSUE TITLE
GridMap iterator col-major order or row-major order ?

### ISSUE THREAD

**Issue by rookiepig** [ethz-asl/grid_map#80]
I am using the 1.4.1 version (apt-get install of ubuntu packages).

I run the iterator_demo, the iterator goes in column-major order, however the gif image of this github repo shows that the iterator goes in row-major order.

I am confused and  want to ask that which one is correct ?

**Comment by pfankhauser** [comment]
Well observed, @rookiepig =) the grid map iterator changed in 1.2.0 to be more efficient. This had the effect that the cell traversal order switched. So the `iterator_demo` is fine, I just haven't gotten around to update the GIF in the documentation.

**Comment by rookiepig** [comment]
Glad to see it fix :+1:    Indeed, I was mislead by the gif :)
