### ISSUE TITLE
New indigo/kinetic releases?

### ISSUE THREAD

**Issue by stonier** [ethz-asl/grid_map#82]
Getting ready to release the cost map counterparts to this library and just realised the debs aren't up to date with the api I'm making use of here in the master branch.

@pfankhauser any chance you can bump a new release on these?

**Comment by pfankhauser** [comment]
Yes of course, I will make a new release as soon as I'm back in the office beginning of January.

**Comment by pfankhauser** [comment]
Here we go: https://github.com/ethz-asl/grid_map/releases/tag/1.4.2
It's being added to rosdistro right now. Thanks for your patience, @stonier.

**Comment by stonier** [comment]
```
     _  _(o)_(o)_  _
   ._\`:_ F S M _:' \_,
       / (`---'\ `-.
    ,-`  _)    (_,
```
