### ISSUE TITLE
changeResolution cause segfault with wrong startIndex

### ISSUE THREAD

**Issue by mcamurri** [ethz-asl/grid_map#91]
I think there's a bug with `GridMapCvProcessing`.

If I have a map of fixed area at high resolution (say, 4 x 4 meters, 1 cm) and I want the same area at low resolution (say 4 x 4 meters, 4 cm) by applying the `changeResolution` method, [this line](https://github.com/ethz-asl/grid_map/blob/master/grid_map_cv/src/GridMapCvProcessing.cpp#L57) causes segfault if the starting index of the original map at high resolution is out of bounds of the target map.

The new starting index should be somehow scaled as well, to find the closest cell to the original in the low resolution map.

**Comment by pfankhauser** [comment]
Hi Marco! Thanks for the notification and please excuse the late response. You are right, the `changeResolution` method was not handling all cases of the buffer correctly. Additionally, by when fixing this, I also found two more errors in the circular and ellipse iterators.

I just pushed the fixes (including unit tests) [here](https://github.com/ethz-asl/grid_map/commit/553f11c736dca800142d61db7a159c784f479314) and things should be working as expected now. Please let me know if you still experience any difficulties.
